---
name: update

on:
  schedule:
    - cron: '30 9 * * SUN'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update
        run: /bin/bash update.sh

      - name: Test
        uses: kohlerdominik/docker-run-action@v1
        with:
          image: eclipse-temurin:17.0.6_10-jre
          volumes: ${{ github.workspace }}:/workspace
          workdir: /workspace
          run: |
            /bin/bash install.sh
            cp ruleset.xml /opt
            /bin/bash run_pmd.sh sample/SampleClass.java
            /bin/bash run_cpd.sh sample/SampleClass.java
            /bin/bash run_checkstyle.sh sample/SampleClass.java

      - name: Tag
        run: /bin/bash tag.sh
